### ISSUE TITLE
Long load times when loading players

### ISSUE THREAD

**Issue by UniversalGleam** [AdKats/BFAdminCP#264]
Hi,

Since roughly 2 weeks ago loading players is taking about 30 seconds on average. I have noticed other people with these panels are experiencing similar issues.

I am running the panel on IIS and it has been working flawlessly for over a year. The rest of the panel works as fast as it ever did.

Do you have any ideas what could be causing the issue?

**Comment by nielsvf** [comment]
I have this too.

**Comment by Prophet731** [comment]
I have not kept up with anything battlefield related and this is the first time I've heard of this issue. If your talking about loading the player profile then it could be the player links causing the delay. I'm not sure, the other sections are loaded dynamically so it shouldn't affect the actual page load time.

**Comment by UniversalGleam** [comment]
Thanks for your reply.

Here is the network tab if you are interested.

http://prntscr.com/g8oriw

**Comment by Graymanflo** [comment]
Bump!

I get exactly the same time as above user when loading a new profile (31s), any reason for this? Thanks.

**Comment by Prophet731** [comment]
@Graymanflo

Yeah it's probably trying to load a third party site which is taking a bit to return the response. I'll be fixing that in my revision update which will be for php 7. I'm rebuilding the entire application again from the ground up due to php 7. So I'll be able to take advantage of the new things in that version.
