### ISSUE TITLE
Request: Allow multiple bans on a single player

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/BFAdminCP#62]
Hello

On the panel, when issuing a ban on a player through his profile, I can only select one out of the server I have listed.
But what about a global ban?

Question 1: How do I do that?

Question 2: When there is already an active ban on 1 server, why I cannot issue a second ban? The "issue ban" button disappears when there is an active ban.

**Comment by Prophet731** [comment]
When you issue a ban it's automaticly global. It technically doesn't matter what server you choose and its more for consistency.

**Comment by iraqiboy90** [comment]
But what if I want the ban to only apply to one server?

**Comment by Prophet731** [comment]
You would need to set the server group for each server. So for example, we have two no explosives servers. There server groups currently are set to 0 which is the default for all servers. Since we enforce bans from all our servers we just leave it at that, however, if we only wanted the ban to be enforced on our no explosives servers then we change the servers group to lets say 1 and the rest of our servers are still at 0. 

So now only servers with server group 1 that the player has a ban on will be enforced but he can still join our TDM server.

**Comment by iraqiboy90** [comment]
I thought the server group had to be defined different from the others.
I have a server group nr, different one for each server.

Now, in that case, by bans are not global if I want them to, right?

**Comment by iraqiboy90** [comment]
Btw, what does the server group nr also affect?

**Comment by Prophet731** [comment]
Whats nr?

**Comment by iraqiboy90** [comment]
nr = number

**Comment by Prophet731** [comment]
Ahh ok.

The server group is also used for some statistics by the logger. If the server group is different then all your other servers then those servers wont have that ban enforced.

**Comment by iraqiboy90** [comment]
Is it possible with an option separate for this scenario? in regards to bans?

**Comment by Prophet731** [comment]
As far as I know, no. If you want the bans to be for all your servers just set the server group to 0 or whatever number you want to use.

So it would look like this.

http://i.gyazo.com/11b07dd57ff69ceead0195567dc2c2c8.png

![](http://i.gyazo.com/11b07dd57ff69ceead0195567dc2c2c8.png)

**Comment by iraqiboy90** [comment]
but if I edit the servergroup number on DB, wont that ruin all the stats and other information that depends on the servergroup number, or am I wrong?

**Comment by iraqiboy90** [comment]
and also:

Question 2: When there is already an active ban on 1 server, why I cannot issue a second ban? The "issue ban" button disappears when there is an active ban.

**Comment by Prophet731** [comment]
> but if I edit the servergroup number on DB, wont that ruin all the stats and other information that depends on the servergroup number, or am I wrong?

It shouldn't ruin them. I believe its for the global stats only not individual player stats.

> and also:
> 
> Question 2: When there is already an active ban on 1 server, why I cannot issue a second ban? The "issue ban" button disappears when there is an active ban.

It's the way AdKats works. When you ban someone from in-game it just updates the ban record with the new one. It doesn't make sense to have two different bans for one person. If you want only specific servers to have the ban just set the server groups to the same number.

Example:

Metro and Lockers No Explosives have server group id of 2. So if a ban is set for either metro or locker then it will enforce the bans only on those servers.

For other servers they are set to 0 so they can join those. If you just want them to be globally banned set all servers server group to the same number you picked, like I said above.

**Comment by iraqiboy90** [comment]
This is kind of problematic... I will be then forced to use an external banlist as an alternative to changing the group number.

**Comment by Prophet731** [comment]
What exactly are you trying to do though?

Looking through the stats logger code the server group is only used which the setting overall ranking is set to yes

**Comment by iraqiboy90** [comment]
hmm... This is actually a nice info.

The thing is, just like it were before adkats, we used to have a policy, or "how we used to do stuff":
- Unless cheating, we ban a player on a single server, adding his ban to other servers if the player does the same offence there as well.

**Comment by Prophet731** [comment]
Hmm... That's a weird of of doing it. However, im just use to our policy where when you're ban on one of our servers your banned from all.

Going to tag @ColColonCleaner because this is something he would also need to implement in AdKats. Perhaps this can be added in a test release with the localization setup.

**Comment by iraqiboy90** [comment]
In regards to question 2; Look at this issue:
![why](https://cloud.githubusercontent.com/assets/8139556/6431318/5115c754-c02c-11e4-811a-91ee4ec0c549.PNG)

**Comment by ColColonCleaner** [comment]
@Prophet731 , player bans only apply to all ADK servers because every server is on the same server group. 

In AdKats bans are only enforced for players across the server group the ban is issued on. This was added about a year ago: https://github.com/AdKats/AdKats/issues/294

There is currently no way to have multiple bans per player, spanning multiple server groups.

**Comment by Prophet731** [comment]
>In regards to question 2; Look at this issue:
>![why](https://cloud.githubusercontent.com/assets/8139556/6431318/5115c754-c02c-11e4-811a-91ee4ec0c549.PNG)
>
>The ban is expired, why I cannot issue another one without removing or modifying the old one?

You can't "issue" a new ban because a ban record already exists in the adkats_bans table. Instead of deleting it we just modify it with the new information. 

Just modify the ban with new information. So change the reason, ban notes, server, ban type, ban status, etc...

That's how you "issue" new bans. As long as you set the ban status to active and set the ban type it will be enforced by adkats.

**Comment by ColColonCleaner** [comment]
Wait, you can't issue a new ban to overwrite an existing one? Sounds like a bug.

**Comment by Prophet731** [comment]
No its not a bug. That's how it's been since forever.

**Comment by Prophet731** [comment]
It will create a new record if one of these conditions is met and updates the adkats_bans table with the new record id.

* Banning admin name is different then the one currently set.
* Ban reason is different from the current one
* Ban type is different from the current ban type.

**Comment by ColColonCleaner** [comment]
Oh, so there just isn't an option to create new when one is already existing, missing feature since the start then. This really doesn't apply to this ticket though, maybe a new one should be made to discuss it.

**Comment by Prophet731** [comment]
SIgh...

It's not a missing feature. That's what im trying to get across...

It's just wording.

```PHP

if($player->hasRecentBan())
{
        print "Modify Ban";
}
else
{
        print "Issue Ban";
}
```

**Comment by ColColonCleaner** [comment]
Yeah, it's missing the feature to issue a new ban. Can't issue a new ban, only modify the current one.

Example, recently banned player 1739237. Found two links, one is supposed to edit the current ban, the other to create a new ban. The second redirects to the first...what?

https://gcp.adkgamers.com/acp/adkats/ban/142041/edit
https://gcp.adkgamers.com/acp/adkats/ban/create?id=1739237

**Comment by Prophet731** [comment]
Again its not a missing feature.

If no record exists in the adkats_bans table then it turns into the create link, however, if a record does exist it will show the edit one instead.

You're just modifying it in the adkats_bans table with the ban start and end dates, ban status, latest record id, ban notes when one exists. It creates a NEW record in the adkats_records table if the one of those conditions I said earlier is true.

When a ban is expired it doesn't delete the record in the adkats_bans table. So it will never show the issue button again because a record for the player already exists.

**Comment by Prophet731** [comment]
The redirect i'll need to check as that's weird.

**Comment by iraqiboy90** [comment]
"There is currently no way to have multiple bans per player, spanning multiple server groups."
Well... we cant have both; Ban by server group and global ban? why not just switch it to "Ban by server ID"?

""You're just modifying it in the adkats_bans table with the ban start and end dates, ban status, latest record id, ban notes when one exists. It creates a NEW record in the adkats_records table if the one of those conditions I said earlier is true.""
Well, what if the reason was not properly written and the admin had to "correct" it, then that would create a new record and make it show as if the admin banned the player twice? This will also add double the amount of negative reputation to the player

**Comment by Prophet731** [comment]
> Well, what if the reason was not properly written and the admin had to "correct" it, then that would create a new record and make it show as if the admin banned the player twice? This will also add double the amount of negative reputation to the player

No it won't cause more negative reputation nor have two active bans on them. There were 2 commands added to prevent that. It just shows as a previous ban under the command action column.

**Comment by iraqiboy90** [comment]
But doesnt "previous" bans give bad reputation?

**Comment by Prophet731** [comment]
> But doesnt "previous" bans give bad reputation?

They still get bad rep but its not a major hit like it is when its set to perma/temp ban for the command action.

**Comment by ColColonCleaner** [comment]
No they don't. The previous ban assignment reduces the reputation change of that record to zero. The new ban record is then used as the reputation changer for that player.

**Comment by Prophet731** [comment]
> No they don't. The previous ban assignment reduces the reputation change of that record to zero. The new ban record is then used as the reputation modifier for that player.

Your right. My mistake.

**Comment by iraqiboy90** [comment]
hmm... But that doesnt seem to be the case when just disabling the current ban

**Comment by Prophet731** [comment]
This will be added in AdKats 7.0.0

**Comment by iraqiboy90** [comment]
:+1: 
I've been reading through the thread on the AFK forums just now.
The least I can say is that I'm very thankful for the great work and time you guys put into these services :)

I will be looking up to Adkats 7 and BFAdminCP 2 :)

**Comment by ColColonCleaner** [comment]
A lot of tickets are going to be moved around because of this. If things go as planned almost every section is changing, including all settings sections and most database tables.
I will be posting a thread with all of the planned redesign changes on MyRCON once they are ready. Either this weekend or next week after BFH launch.

**Comment by iraqiboy90** [comment]
:+1:
